from __future__ import annotations

from typing import Any, Dict


def build_handler_map(*, deps: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "root": deps["root"],
        "health": deps["health"],
        "history": deps["history"],
        "download_file": deps["download_file"],
        "get_rollouts": deps["get_rollouts"],
        "clear_rollouts": deps["clear_rollouts"],
        "delete_rollout": deps["delete_rollout"],
        "get_rollout_spans": deps["get_rollout_spans"],
        "get_statistics": deps["get_statistics"],
        "get_artifacts": deps["get_artifacts"],
        "get_metrics_overview": deps["get_metrics_overview"],
        "list_training_runs": deps["list_training_runs"],
        "clear_training_runs": deps["clear_training_runs"],
        "get_training_file": deps["get_training_file"],
        "publish_training_result": deps["publish_training_result"],
        "get_prompt_versions": deps["get_prompt_versions"],
        "update_prompt_versions": deps["update_prompt_versions"],
        "get_current_prompts": deps["get_current_prompts"],
        "update_current_prompts": deps["update_current_prompts"],
        "list_schema_files": deps["list_schema_files"],
        "get_schema_file": deps["get_schema_file"],
        "update_schema_file": deps["update_schema_file"],
        "start_rl_job": deps["start_rl_job"],
        "stop_rl_job": deps["stop_rl_job"],
        "list_rl_jobs": deps["list_rl_jobs"],
        "list_rl_task_history": deps["list_rl_task_history"],
        "api_memory_build": deps["api_memory_build"],
        "api_memory_search": deps["api_memory_search"],
        "api_memory_stats": deps["api_memory_stats"],
        "api_memory_backfill": deps["api_memory_backfill"],
        "api_memory_clear": deps["api_memory_clear"],
        "delete_memory": deps["delete_memory"],
        "api_memory_usages": deps["api_memory_usages"],
        "api_memory_usage_events": deps["api_memory_usage_events"],
        "api_memory_quality": deps["api_memory_quality"],
        "api_memory_aliases": deps["api_memory_aliases"],
        "api_memory_alias_review": deps["api_memory_alias_review"],
        "chat_resume_context": deps["chat_resume_context"],
        "get_rl_job": deps["get_rl_job"],
        "stop_chat_stream": deps["stop_chat_stream"],
        "chat_resume_stream": deps["chat_resume_stream"],
        "chat_stream": deps["chat_stream"],
        "get_model_config": deps["get_model_config"],
        "save_model_config": deps["save_model_config"],
        "test_model_config": deps["test_model_config"],
        "get_system_config": deps["get_system_config"],
        "save_system_config": deps["save_system_config"],
        "test_system_config": deps["test_system_config"],
        "restart_service": deps["restart_service"],
    }


